apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: opstools
  name: opstools
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opstools
  template:
    metadata:
      labels:
        app: opstools
    spec:
      containers:
      - args:
        - bash
        - -c
        - while true; do sleep 3600; done
        image: elisiano/opstools
        name: opstools
